name: Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine Version
        id:   version
        uses: frabert/replace-string-action@v1.1
        with:
          pattern:      '^refs.tags.v'
          string:       ${{ github.ref }}
          replace-with: ''

      - name: Build Blacksmith
        run: |
          make VERSION=${{ steps.version.outputs.replaced }} shipit
      
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: "false"

      - name: Create Release
        id:   release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          tag_name:     ${{ github.ref }}
          release_name: Blacksmith ${{ github.ref }}
          draft:        false
          prerelease:   false
          body: ${{ steps.changelog.outputs.clean_changelog }}

      - name: Upload Release Tarball
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./artifacts/blacksmith-${{ steps.version.outputs.replaced }}.tar.bz2
          asset_name: blacksmith-${{ steps.version.outputs.replaced }}.tar.bz2
          asset_content_type: application/octet-stream

      - name: Upload Blacksmith for Linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./artifacts/blacksmith-linux-amd64
          asset_name: blacksmith-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Blacksmith for Linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./artifacts/blacksmith-darwin-amd64
          asset_name: blacksmith-darwin-amd64
          asset_content_type: application/octet-stream
